### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Alexey-T** [eastorwest/cuda_openfiles#1]
если открыто 10 файлов - клик любого таба дает паузу 2с.
Вы ловите onfocus и делаете выделение tree.
оно вызывает on_panel/on_sel и оно открывает файл. он уже открыт.

**Comment by eastorwest** [comment]
Внес изменения для исправления повторного вызова, а также для исправления сворачивания при открытии файла.

**Comment by Alexey-T** [comment]
Стало Ок
