### ISSUE TITLE
Open dir

### ISSUE THREAD

**Issue by Alexey-T** [eastorwest/cuda_openfiles#2]
Открываю папку через File-OpenFolder
думал ничего нет. а есть-открылось в дерево, но не было разворачивания этого нового. надо или разворачивать хоть 1 уровень (до папки) или все папки. и потом надо ставить выделение на новую папку.

посм. как Субл делает.

**Comment by eastorwest** [comment]
Выделение добавленной папки после ее открытия сделано.
