### ISSUE TITLE
Enc filename

### ISSUE THREAD

**Issue by Alexey-T** [eastorwest/cuda_openfiles#7]
~~~
   # "convert" file name encoding in Python 3.x... tested only on Windows, no Linux     
      a_file = bytes(a_file, sys.getfilesystemencoding()).decode('utf-8')    
~~~
по-моему не надо.Никогда такой кодировки не делал, в Пи3 все в юникоде (Пи2 нет)

**Comment by eastorwest** [comment]
Тестировал на Windows XP SP3 x32 добавление папки через File - Open folder. Получил неудовлетворительный результат, русские буквы не отображались и сам путь не определялся в плагине, как существующий. Вот эта строчка далась с трудом, пришлось искать в Интернете путь преобразования кодировок. Возможно, функция API dlg_file возвращает на Win32 путь в кодировке ANSI, поэтому так и происходит.

**Comment by Alexey-T** [comment]
Ну это баг,явно же.Внес правку,проверил, в гит

**Comment by Alexey-T** [comment]
Все строки должны быть у меня unicode

**Comment by eastorwest** [comment]
Баг Lazarus.LCL?

**Comment by Alexey-T** [comment]
нет- я возвращал ansi string

**Comment by eastorwest** [comment]
Удалил преобразование кодировок после обновления git и проверки.
